DOMAIN = "battery_storage_roi"

CONF_START_DATE = "start_date"
CONF_INSTALL_COST = "install_cost_eur"
CONF_GRID_PRICE = "grid_price_eur_per_kwh"
CONF_FEEDIN_PRICE = "feedin_price_eur_per_kwh"
CONF_CHARGED_ENTITY = "charged_kwh_entity"
CONF_DISCHARGED_ENTITY = "discharged_kwh_entity"
CONF_INCLUSIVE_DAYS = "inclusive_days"
CONF_BASELINE_CHARGED = "baseline_charged_kwh"
CONF_BASELINE_DISCHARGED = "baseline_discharged_kwh"
CONF_USABLE_CAPACITY = "usable_capacity_kwh"

# attributes / keys
ATTR_DAYS = "days_in_operation"
ATTR_EFFICIENCY = "efficiency_percent"
ATTR_SAVINGS_GROSS = "avoided_grid_costs_eur"
ATTR_OPPORTUNITY = "opportunity_costs_eur"
ATTR_NET_BENEFIT = "net_benefit_eur"
ATTR_NET_DAILY = "net_benefit_per_day_eur"
ATTR_ROI_REMAINING = "roi_days_remaining"
ATTR_ROI_DATE = "roi_date"
ATTR_INPUTS_OK = "inputs_ok"
ATTR_CHARGED_DELTA = "charged_since_start_kwh"
ATTR_DISCHARGED_DELTA = "discharged_since_start_kwh"
ATTR_MONEY_EFF_OUT = "money_eff_out_eur_per_kwh_out"
ATTR_MONEY_EFF_IN = "money_eff_in_eur_per_kwh_in"
ATTR_SNY = "specific_net_yield_eur_per_kwhcap_day"
ATTR_CYCLES_PER_DAY = "cycles_per_day"
